//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 12:51:07 PM CAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://modusbps.com/bos/nugget-web-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.modusbps.bos.nugget_web_service;
